# Generated by Django 2.2.1 on 2021-08-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_postal', models.IntegerField(verbose_name='Código Postal')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('UserName', models.CharField(max_length=50, verbose_name='Usuario')),
                ('Llave', models.CharField(max_length=50, verbose_name='Llave')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('DNI', models.CharField(max_length=50, verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Pais', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('avenida', models.CharField(max_length=100, verbose_name='Avenida')),
                ('numero_casa', models.IntegerField(verbose_name='Numero Casa')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Region', verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre1', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('nombre2', models.CharField(max_length=50, verbose_name='Segundo nombre')),
                ('apellido1', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('apellido2', models.CharField(max_length=50, verbose_name='Segundo apellido')),
                ('numero_celular', models.CharField(max_length=8, verbose_name='Segundo nombre')),
                ('numero_telefono', models.CharField(max_length=8, verbose_name='Segundo nombre')),
                ('email', models.CharField(max_length=50, verbose_name='Segundo nombre')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Direccion', verbose_name='Direccion')),
            ],
        ),
    ]
